// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CommoditiesDao is the data access object for table commodities.
type CommoditiesDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns CommoditiesColumns // columns contains all the column names of Table for convenient usage.
}

// CommoditiesColumns defines and stores column names for table commodities.
type CommoditiesColumns struct {
	Id         string // 商品ID
	Name       string // 商品名称
	ClassifyId string // 分类ID
	Des        string // 商品描述
	CreatedAt  string // 创建时间
	UpdatedAt  string // 更新时间
	DeletedAt  string // 删除时间
}

// commoditiesColumns holds the columns for table commodities.
var commoditiesColumns = CommoditiesColumns{
	Id:         "id",
	Name:       "name",
	ClassifyId: "classify_id",
	Des:        "des",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	DeletedAt:  "deleted_at",
}

// NewCommoditiesDao creates and returns a new DAO object for table data access.
func NewCommoditiesDao() *CommoditiesDao {
	return &CommoditiesDao{
		group:   "default",
		table:   "commodities",
		columns: commoditiesColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CommoditiesDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CommoditiesDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CommoditiesDao) Columns() CommoditiesColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CommoditiesDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CommoditiesDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CommoditiesDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
