// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "401-company/internal/logic/classify"
	_ "401-company/internal/logic/commodity"
)
