
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:

  #  工具编译配置
  build:
    name: "gf-admin-community"
    arch: "amd64"
    system: "linux,darwin,windows"
    mod: ""
    cgo: 0


  #  dao生成
  gen:
    dao:
      - link: "pgsql:user=kuaimk password=Kuaimk23db host=192.168.1.105 port=5432 dbname=zjy sslmode=disable"
        tables: "classify,commodities"
        descriptionTag: true
        noModelComment: true
        withTime: false
