// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Classify is the golang structure of table classify for DAO operations like Where/Data.
type Classify struct {
	g.Meta    `orm:"table:classify, do:true"`
	Id        interface{} // 分类ID
	Name      interface{} // 分类名称
	ParentId  interface{} // 父级ID
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
}
