// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Commodities is the golang structure of table commodities for DAO operations like Where/Data.
type Commodities struct {
	g.Meta     `orm:"table:commodities, do:true"`
	Id         interface{} // 商品ID
	Name       interface{} // 商品名称
	ClassifyId interface{} // 分类ID
	Des        interface{} // 商品描述
	CreatedAt  *gtime.Time // 创建时间
	UpdatedAt  *gtime.Time // 更新时间
	DeletedAt  *gtime.Time // 删除时间
}
