// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"401-company/model"
	"401-company/model/entity"
	"context"
)

type (
	IClassify interface {
		CreateClassify(ctx context.Context, info model.Classify) (*entity.Classify, error)
		UpdateClassify(ctx context.Context, info model.Classify) (*entity.Classify, error)
		SaveClassify(ctx context.Context, info model.Classify) (*entity.Classify, error)
		QueryClassify(ctx context.Context, id int64) (*entity.Classify, error)
		DeleteClassify(ctx context.Context, id int64) (bool, error)
	}
)

var (
	localClassify IClassify
)

func Classify() IClassify {
	if localClassify == nil {
		panic("implement not found for interface IClassify, forgot register?")
	}
	return localClassify
}

func RegisterClassify(i IClassify) {
	localClassify = i
}
