// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"401-company/model"
	"401-company/model/entity"
	"context"
)

type (
	ICommodity interface {
		CreateCommodity(ctx context.Context, info model.Commodity) (*entity.Commodities, error)
		UpdateCommodity(ctx context.Context, info model.Commodity) (*entity.Commodities, error)
		SaveCommodity(ctx context.Context, info model.Commodity) (*entity.Commodities, error)
		QueryCommodity(ctx context.Context, id int64) (*entity.Commodities, error)
		DeleteCommodity(ctx context.Context, id int64) (bool, error)
	}
)

var (
	localCommodity ICommodity
)

func Commodity() ICommodity {
	if localCommodity == nil {
		panic("implement not found for interface ICommodity, forgot register?")
	}
	return localCommodity
}

func RegisterCommodity(i ICommodity) {
	localCommodity = i
}
