// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"401-company/model/dao/internal"
)

// internalClassifyDao is internal type for wrapping internal DAO implements.
type internalClassifyDao = *internal.ClassifyDao

// classifyDao is the data access object for table classify.
// You can define custom methods on it to extend its functionality as you wish.
type classifyDao struct {
	internalClassifyDao
}

var (
	// Classify is globally public accessible object for table classify operations.
	Classify = classifyDao{
		internal.NewClassifyDao(),
	}
)

// Fill with you ideas below.
