// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"401-company/model/dao/internal"
)

// internalCommoditiesDao is internal type for wrapping internal DAO implements.
type internalCommoditiesDao = *internal.CommoditiesDao

// commoditiesDao is the data access object for table commodities.
// You can define custom methods on it to extend its functionality as you wish.
type commoditiesDao struct {
	internalCommoditiesDao
}

var (
	// Commodities is globally public accessible object for table commodities operations.
	Commodities = commoditiesDao{
		internal.NewCommoditiesDao(),
	}
)

// Fill with you ideas below.
