// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Commodities is the golang structure for table commodities.
type Commodities struct {
	Id         int64       `json:"id"         description:"商品ID"`
	Name       string      `json:"name"       description:"商品名称"`
	ClassifyId int64       `json:"classifyId" description:"分类ID"`
	Des        string      `json:"des"        description:"商品描述"`
	CreatedAt  *gtime.Time `json:"createdAt"  description:"创建时间"`
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:"更新时间"`
	DeletedAt  *gtime.Time `json:"deletedAt"  description:"删除时间"`
}
